version: "3.8"

services:
  api:
    container_name: api
    image: mdaniel543/api
    ports:
      - "3000:3000"
    restart: always
    networks:
      - shared

  web:
    container_name: web
    image: mdaniel543/web
    ports:
      - "4000:80"
    restart: always
    depends_on:
      - api
    networks: 
      - shared

networks:
  shared:

