version: "3"

services:
  api:
    container_name: api
    image: mdaniel543/api
    ports:
      - "3000:3000"
    restart: always

  web:
    container_name: web
    image: web
    build: ./web
    ports:
      - "4000:80"
    restart: always
    depends_on:
      - api
    links:
      - api
